In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
df = pd.read_csv("/content/bank.csv",sep=";")
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [23]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder

# Example: Assuming 'education' is a categorical variable
label_encoder = LabelEncoder()
df['job_encoded'] = label_encoder.fit_transform(df['job'])
df.drop('job', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['education_encoded'] = label_encoder.fit_transform(df['education'])
df.drop('education', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['marital_encoded'] = label_encoder.fit_transform(df['marital'])
df.drop('marital', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['default_encoded'] = label_encoder.fit_transform(df['default'])
df.drop('default', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['housing_encoded'] = label_encoder.fit_transform(df['housing'])
df.drop('housing', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['loan_encoded'] = label_encoder.fit_transform(df['loan'])
df.drop('loan', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['contact_encoded'] = label_encoder.fit_transform(df['contact'])
df.drop('contact', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['month_encoded'] = label_encoder.fit_transform(df['month'])
df.drop('month', axis=1, inplace=True)

label_encoder = LabelEncoder()
df['poutcome_encoded'] = label_encoder.fit_transform(df['poutcome'])
df.drop('poutcome', axis=1, inplace=True)

In [25]:
df

,age,balance,day,duration,campaign,pdays,previous,y,job_encoded,education_encoded,marital_encoded,default_encoded,housing_encoded,loan_encoded,contact_encoded,month_encoded,poutcome_encoded
0,30,1787,19,79,1,-1,0,no,10,0,1,0,0,0,0,10,3
1,33,4789,11,220,1,339,4,no,7,1,1,0,1,1,0,8,0
2,35,1350,16,185,1,330,1,no,4,2,2,0,1,0,0,0,0
3,30,1476,3,199,4,-1,0,no,4,2,1,0,1,1,2,6,3
4,59,0,5,226,1,-1,0,no,1,1,1,0,1,0,2,8,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,-333,30,329,5,-1,0,no,7,1,1,0,1,0,0,5,3
4517,57,-3313,9,153,1,-1,0,no,6,2,1,1,1,1,2,8,3
4518,57,295,19,151,11,-1,0,no,9,1,1,0,0,0,0,1,3
4519,28,1137,6,129,4,211,3,no,1,1,1,0,0,0,0,3,1
4520,44,1136,3,345,2,249,7,no,2,2,2,0,1,1,0,0,1

In [27]:
X = df.drop('y', axis=1)
y = df['y']

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


dt_classifier = DecisionTreeClassifier(random_state=42)

dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_test)

accuracy_test = accuracy_score(y_test, y_pred)
accuracy_train = accuracy_score(y_train, y_train)

print(f'accuracy_test: {accuracy_test}')
print(f'accuracy_train: {accuracy_train}')

accuracy_test: 0.8773480662983425
accuracy_train: 1.0